In [13]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

import joblib

In [14]:
df=pd.read_csv("../data/processed/telco_churn_cleaned.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,ChurnFlag
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,0
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1

In [15]:
X=df.drop(columns=["customerID","Churn","ChurnFlag"])

In [16]:
y=df["ChurnFlag"]

In [17]:
categorical_cols=X.select_dtypes(include=["object"]).columns
numerical_cols=X.select_dtypes(include=["int64","float64"]).columns

C:\Users\swaya\AppData\Local\Temp\ipykernel_19160\2276821725.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols=X.select_dtypes(include=["object"]).columns

In [18]:
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

In [19]:
preprocessor=ColumnTransformer(
    transformers=[
        ("num",StandardScaler(),numerical_cols),
        ("cat",OneHotEncoder(handle_unknown="ignore"),categorical_cols)
    ]
)

In [20]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42)
}

In [23]:
results=[]
for name,model in models.items():
    clf=Pipeline(
        steps=[
            ("preprocessor",preprocessor),
            ("model",model)
        ]
    )
    clf.fit(X_train,y_train)

    y_pred=clf.predict(X_test)
    y_proba=clf.predict_proba(X_test)[:,1]

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1": f1_score(y_test, y_pred),
        "ROC_AUC": roc_auc_score(y_test, y_proba)
    })

results_df = pd.DataFrame(results)
results_df

                 Model  Accuracy  Precision    Recall        F1   ROC_AUC
0  Logistic Regression  0.805536   0.657233  0.558824  0.604046  0.841874
1        Random Forest  0.777857   0.603390  0.475936  0.532138  0.816366
2    Gradient Boosting  0.806246   0.673540  0.524064  0.589474  0.843212

In [24]:
best_model=Pipeline(
    steps=[
        ("preprocessor",preprocessor),
        ("model",GradientBoostingClassifier(random_state=42))
    ]
)
best_model.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str'))])),
                ('model', GradientBoostingClassifier(random_state=42))])

In [25]:
joblib.dump(best_model,"../models/gradient_boosting_churn_model.pkl")

['../models/gradient_boosting_churn_model.pkl']

In [26]:
import os

os.path.exists("../models/gradient_boosting_churn_model.pkl")

True

In [27]:
y_pred = best_model.predict(X_test)
y_proba = best_model.predict_proba(X_test)[:, 1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1:", f1_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_proba))

Accuracy: 0.8062455642299503
Precision: 0.6735395189003437
Recall: 0.5240641711229946
F1: 0.5894736842105263
ROC-AUC: 0.8432121728796921

In [30]:
df_scored=df.copy()
df_scored["ChurnProbablity"]=best_model.predict_proba(X)[:,1]

In [31]:
df_scored["riskSegment"]=pd.cut(
    df_scored["ChurnProbablity"],
    bins=[0,0.33,0.66,1],
    labels=["low","medium","high"],
    include_lowest=True
)

In [32]:
df_scored[["customerID","Churn","ChurnProbablity","riskSegment"]].head()

   customerID Churn  ChurnProbablity riskSegment
0  7590-VHVEG    No         0.487798      medium
1  5575-GNVDE    No         0.048455         low
2  3668-QPYBK   Yes         0.339647      medium
3  7795-CFOCW    No         0.043462         low
4  9237-HQITU   Yes         0.639792      medium

In [33]:
df_scored["riskSegment"].value_counts()

riskSegment
low       4665
medium    1642
high       736
Name: count, dtype: int64

In [34]:
df_scored.to_csv("../outputs/churn_scored_customers.csv",index=False)

In [35]:
import os

os.path.exists("../outputs/churn_scored_customers.csv")

True